version: "3.2"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=clickup_integration
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=3306
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db-data:
